### ISSUE TITLE
missing variable in code

### ISSUE THREAD

**Issue by ghost** [iebayirli/NavigationDemo#1]
Hi

thanks for the tut
though there is one thing that is not clear. what is BR in here?
https://github.com/iebayirli/NavigationDemo/blob/master/app/src/main/java/com/iebayirli/navigationdemo/base/BaseFragment.kt#L41

I can't find in the code and I am not sure what it is used for

**Comment by iebayirli** [comment]
Hi, thank you for interest.

These variables comes from DataBinding library. Library generates this variable (i suppose) in compile time. When you use DataBinding in your project you can add variables into your layouts and reach them in Activity/Fragment.

Please refer this documentatin and DataBinding examples. You will understand the concept.

https://developer.android.com/topic/libraries/data-binding/generated-binding
